CREATE TABLE IF NOT EXISTS companies (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    web_url VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    img TEXT,
    industry VARCHAR(255) NOT NULL,
    scrape_target_url VARCHAR(255) NOT NULL,
    last_scrape_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
